// Generated by scripts/build_images.py. Do not edit by hand.
export const imageManifest = {
  "mitten": {
    "tip_x": 3779,
    "x_r": 3539,
    "warp_start": 3200,
    "copy_dy": -5,
    "thumb_base": [
      3355,
      1156
    ],
    "thumb_angle": 38.0,
    "hand_len": 819,
    "fleece_len": 2340,
    "hand_ratio": 0.35
  },
  "flatlay": {
    "w": 3731,
    "h": 1316,
    "sizes": [
      {
        "w": 960,
        "h": 339
      },
      {
        "w": 1600,
        "h": 564
      },
      {
        "w": 2400,
        "h": 847
      }
    ]
  },
  "hotspots": {
    "strap": {
      "x": 13.24,
      "y": 32.52
    },
    "pouch": {
      "x": 30.66,
      "y": 40.88
    },
    "fleece": {
      "x": 60.14,
      "y": 53.8
    },
    "mitten": {
      "x": 92.71,
      "y": 51.9
    }
  },
  "vertical": {
    "w": 1270,
    "h": 3771,
    "sizes": [
      {
        "w": 480,
        "h": 1425
      },
      {
        "w": 720,
        "h": 2138
      },
      {
        "w": 1200,
        "h": 3563
      }
    ]
  },
  "hotspotsVertical": {
    "strap": {
      "x": 64.96,
      "y": 13.1
    },
    "pouch": {
      "x": 56.3,
      "y": 30.34
    },
    "fleece": {
      "x": 42.91,
      "y": 59.51
    },
    "mitten": {
      "x": 44.88,
      "y": 91.73
    }
  },
  "crops": {
    "fleece": {
      "w": 640,
      "h": 480,
      "sizes": [
        {
          "w": 320,
          "h": 240
        },
        {
          "w": 640,
          "h": 480
        }
      ]
    },
    "strap": {
      "w": 720,
      "h": 540,
      "sizes": [
        {
          "w": 320,
          "h": 240
        },
        {
          "w": 640,
          "h": 480
        }
      ]
    },
    "pouch": {
      "w": 720,
      "h": 540,
      "sizes": [
        {
          "w": 320,
          "h": 240
        },
        {
          "w": 640,
          "h": 480
        }
      ]
    },
    "mitten": {
      "w": 1160,
      "h": 870,
      "sizes": [
        {
          "w": 320,
          "h": 240
        },
        {
          "w": 640,
          "h": 480
        }
      ]
    },
    "wrist-seam": {
      "w": 680,
      "h": 550,
      "sizes": [
        {
          "w": 480,
          "h": 388
        },
        {
          "w": 680,
          "h": 550
        }
      ]
    }
  },
  "refFlatlay": {
    "w": 3774,
    "h": 1783,
    "sizes": [
      {
        "w": 560,
        "h": 265
      },
      {
        "w": 1120,
        "h": 529
      }
    ]
  },
  "refWorn": {
    "w": 567,
    "h": 1688,
    "sizes": [
      {
        "w": 280,
        "h": 834
      },
      {
        "w": 567,
        "h": 1688
      }
    ]
  },
  "logo": {
    "w": 2872,
    "h": 716,
    "sizes": [
      {
        "w": 176,
        "h": 44
      },
      {
        "w": 232,
        "h": 58
      },
      {
        "w": 352,
        "h": 88
      },
      {
        "w": 464,
        "h": 116
      },
      {
        "w": 528,
        "h": 132
      },
      {
        "w": 696,
        "h": 174
      }
    ]
  },
  "faviconSvg": true
} as const;
