import type { ImageSet } from '../content/images';
import { largest, srcset } from '../content/images';

type ArtSource = { media: string; image: ImageSet; sizes: string };

type Props = {
  image: ImageSet;
  alt: string;
  sizes: string;
  className?: string;
  imgClassName?: string;
  priority?: boolean;
  /** Art-directed alternatives, checked before the default image. */
  art?: ArtSource[];
};

/** Responsive <picture> with AVIF / WebP / PNG-or-JPEG sources and explicit
 * dimensions, generated by scripts/build_images.py. */
export function Picture({ image, alt, sizes, className, imgClassName, priority, art = [] }: Props) {
  const fb = largest(image.name, image.sizes, image.fallback);
  return (
    <picture className={className}>
      {art.flatMap((a) =>
        ['avif', 'webp', a.image.fallback].map((ext) => (
          <source
            key={`${a.media}-${ext}`}
            media={a.media}
            type={ext === 'avif' ? 'image/avif' : ext === 'webp' ? 'image/webp' : ext === 'png' ? 'image/png' : 'image/jpeg'}
            srcSet={srcset(a.image.name, a.image.sizes, ext)}
            sizes={a.sizes}
            width={a.image.w}
            height={a.image.h}
          />
        )),
      )}
      <source type="image/avif" srcSet={srcset(image.name, image.sizes, 'avif')} sizes={sizes} />
      <source type="image/webp" srcSet={srcset(image.name, image.sizes, 'webp')} sizes={sizes} />
      <img
        className={imgClassName}
        src={fb.src}
        srcSet={srcset(image.name, image.sizes, image.fallback)}
        sizes={sizes}
        width={image.w}
        height={image.h}
        alt={alt}
        decoding={priority ? 'sync' : 'async'}
        loading={priority ? 'eager' : 'lazy'}
        // React 19 passes fetchPriority through to the DOM attribute
        fetchPriority={priority ? 'high' : 'auto'}
      />
    </picture>
  );
}
