#!/usr/bin/env python3
"""Build every web image for the WARMUP site from source-assets/.

    python3 scripts/build_images.py      (or: npm run images)

Pipeline (Tier A photo composite, see docs/DESIGN_PLAN.md §7):
  1. segment the flat lay from the cutting mat (B-G key), soft alpha
  2. defringe edges against the local mat colour, remove green spill
  3. white-balance so the fleece reads as cream
  4. extend the rib-knit hand section into an integrated mitten + thumb
  5. contact shadow, responsive exports (horizontal + vertical)
  6. detail crops, untouched prototype references, logo, favicons, OG image
Writes a manifest to .cache/images/manifest.json, consumed by
src/content/images.generated.ts, and review crops to docs/pipeline/.
"""
import json
import sys
from pathlib import Path

import numpy as np
from PIL import Image

sys.path.insert(0, str(Path(__file__).resolve().parent))

from imgpipe import segment, mitten, export  # noqa: E402
from imgpipe.paths import CACHE, DOCS_PIPE, ROOT  # noqa: E402

# Feature positions in full-resolution flat-lay coordinates (docs/ASSETS.md §3)
HOTSPOTS = {
    "strap": (600, 650),     # charcoal strap with the white hook-and-loop strip
    "pouch": (1250, 760),    # patch pouch, right of its bound slot
    "fleece": (2350, 930),   # forearm fleece
    "mitten": (3565, 905),   # finger chamber of the mitten
}

# Feature outlines (left, top, right, bottom) in composite coordinates, used
# to draw a subtle outline around the selected feature in the anatomy view
FEATURE_BOXES = {
    "strap": (290, 320, 915, 925),
    "pouch": (835, 470, 1520, 1215),
    "fleece": (1600, 500, 2920, 1340),
    "mitten": (2915, 610, 3795, 1395),
}

# Detail crops (left, top, right, bottom) in composite coordinates
CROPS = {
    # real-photo detail: cuff rib + hook patch, strap with hook-and-loop strip,
    # pouch with its bound slot (no mitten pixels)
    "fastening": ((360, 420, 1160, 1340), [480, 800]),
    "fleece": ((2050, 900, 2690, 1380), [320, 640]),
    "strap": ((210, 300, 930, 840), [320, 640]),
    "pouch": ((760, 470, 1480, 1010), [320, 640]),
    "mitten": ((2860, 560, 4020, 1430), [320, 640]),
    "wrist-seam": ((2560, 640, 3240, 1190), [480, 680]),
}
CROP_BG = (237, 242, 251)  # --surface-blue


def review_crops(rgb, a):
    """100% and 200% crops of the composite for visual inspection."""
    img = export.flatten_on(export.to_image(rgb, a), (247, 249, 252))
    img.crop((2700, 450, 4034, 1550)).save(DOCS_PIPE / "mitten-100.jpg", quality=90)
    # bottom fleece edge at 200%: check for an extraction rim / halo
    img.crop((1700, 1120, 2300, 1320)).resize((1200, 400), Image.LANCZOS).save(DOCS_PIPE / "fleece-edge-200.jpg", quality=90)
    img.crop((3450, 700, 3850, 1100)).resize((800, 800), Image.LANCZOS).save(DOCS_PIPE / "mitten-tip-200.jpg", quality=90)
    img.crop((3250, 1050, 3750, 1450)).resize((1000, 800), Image.LANCZOS).save(DOCS_PIPE / "mitten-thumb-200.jpg", quality=90)
    dark = export.flatten_on(export.to_image(rgb, a), (16, 36, 70))
    dark.crop((1600, 1050, 2400, 1450)).resize((1600, 800), Image.LANCZOS).save(DOCS_PIPE / "edge-on-dark-200.jpg", quality=90)


def main():
    print("1-3  segment, defringe, white balance")
    graded, alpha, _ = segment.run()
    print("4    mitten")
    rgb, a, info = mitten.build(graded, alpha)
    print("     ", info)
    review_crops(rgb, a)
    manifest = {"mitten": info}
    print("5    product exports")
    hero, _ = export.export_product(rgb, a, manifest, HOTSPOTS, FEATURE_BOXES)
    print("6    crops, references, logo, favicons, OG")
    export.export_crops(rgb, a, manifest, CROPS, CROP_BG)
    export.export_references(manifest)
    logo = export.export_logo(manifest)
    frac = export.export_favicons(logo)
    manifest["faviconSvg"] = export.export_favicon_svg(frac)
    export.export_og(hero, logo)
    export.write_manifest(manifest)
    ts = ROOT / "src" / "content" / "images.generated.ts"
    ts.parent.mkdir(parents=True, exist_ok=True)
    ts.write_text(
        "// Generated by scripts/build_images.py. Do not edit by hand.\n"
        f"export const imageManifest = {json.dumps(manifest, indent=2)} as const;\n"
    )
    print("done ->", ts.relative_to(ROOT))


if __name__ == "__main__":
    main()
